[package]
name = "engine"
version = "0.0.0"
authors = ["Torbjørn Birch Moltu <t.b.moltu@lyse.net>"]
description = """
Reduce compile times by hiding dependencies in a dylib
and expose custom types and functions for what I need.
"""

# build as dylib in debug mode to reduce compile time,
# but statically in release mode for selfcontained-ness
[lib] # works unconditionally
#[target.'cfg(debug_assertions)'.lib] # doesn't work
#[target.'cfg(feature="dyn")'.lib] # doesn't work eiter
crate-type = ["dylib"]

[dependencies]
piston_window = "0.80"
pistoncore-glutin_window = "0.47"
piston2d-opengl_graphics = "0.53"

[target.'cfg(debug_assertions)'.dependencies]
dlopen = "0.1"

[features]
dyn = []
