[package]
name = "engine"
description = """
Reduce compile times by hiding dependencies in a dylib
and expose custom types and functions for what I need.
"""
version = "0.0.0"
authors = ["Torbjørn Birch Moltu <t.b.moltu@lyse.net>"]
license = "Apache-2 / MIT"

# build as dylib in debug mode to reduce compile time,
# but statically in release mode for selfcontained-ness
[lib] # works unconditionally
#[target.'cfg(debug_assertions)'.lib] # does not have any effect
#[target.'cfg(feature="dyn")'.lib] # doesn't work eiter (given --features=dyn)
crate-type = ["dylib"]

[dependencies]
piston_window = "0.105"
pistoncore-glutin_window = "0.63"
piston2d-opengl_graphics = "0.69"

[target.'cfg(debug_assertions)'.dependencies]
dlopen = "0.1"
notify = "4"
serde_json = "1"
serde_derive = "1"
serde = "1"

[features]
dyn = []
